import pandas as pd
import matplotlib.pyplot as plt

# Read the CSV generated by C program
try:
    df = pd.read_csv('q2_data.csv')
except FileNotFoundError:
    print("Error: Run the C program first to generate q2_data.csv")
    exit()

plt.figure(figsize=(8, 5))

# Plot empirical data vs theoretical bound
plt.plot(df['N'], df['AvgUses'], marker='o', label='Average Scale Uses')
plt.plot(df['N'], df['WorstCase'], marker='s', label='Worst Case Scale Uses')
plt.plot(df['N'], df['Log2N'], marker='^', linestyle='--', color='red', label='Theoretical bound (log2 N)')

plt.title('Defective Coin Search Complexity')
plt.xlabel('Number of Coins (N)')
plt.ylabel('Number of Weighings')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.savefig('q2_plot.png')
print("Graph saved!")